# Generated by Django 2.0.6 on 2018-06-04 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NationalTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_slug', models.SlugField(unique=True)),
                ('team_display_name', models.CharField(max_length=80)),
                ('team_blurb', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('player_slug', models.SlugField(unique=True)),
                ('player_name', models.CharField(max_length=80)),
                ('card_number', models.IntegerField(primary_key=True, serialize=False)),
                ('special_card', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sticker_collection_app.NationalTeam')),
            ],
        ),
    ]
