# Generated by Django 2.0.6 on 2018-06-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_collection_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalteam',
            name='team_order',
            field=models.IntegerField(default=1, help_text='Order of teams in book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sticker',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sticker',
            name='card_number',
            field=models.IntegerField(),
        ),
    ]
