# Generated by Django 2.0.6 on 2018-06-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_collection_app', '0002_auto_20180609_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldCup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2018)),
                ('location', models.CharField(choices=[('WC_1994', 'US 1994'), ('WC_1998', 'France 1998'), ('WC_2002', 'Korea/Japan 2002'), ('WC_2006', 'German 2006'), ('WC_2010', 'South Africa 2010'), ('WC_2014', 'Germany 2014'), ('WC_2018', 'Russia 2018'), ('WC_2022', 'Qatar 2022'), ('WC_2026', 'Canada/Mexico/US 2026')], max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='nationalteam',
            name='team_group',
            field=models.CharField(choices=[('GROUP_A', 'Group A'), ('GROUP_B', 'Group B'), ('GROUP_C', 'Group C'), ('GROUP_D', 'Group D'), ('GROUP_E', 'Group E'), ('GROUP_F', 'Group F'), ('GROUP_G', 'Group G'), ('GROUP_H', 'Group H')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nationalteam',
            name='team_year',
            field=models.IntegerField(default=2018),
        ),
    ]
