# Generated by Django 2.0.6 on 2018-06-16 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_collection_app', '0003_auto_20180616_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldcup',
            name='year',
        ),
        migrations.AlterField(
            model_name='nationalteam',
            name='team_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sticker_collection_app.WorldCup'),
        ),
    ]
