# Generated by Django 2.0.6 on 2018-07-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('sticker_collection_app', '0004_auto_20180616_0347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorldCup',
            new_name='WorldCupAlbum',
        ),
        migrations.AddField(
            model_name='sticker',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nationalteam',
            name='team_slug',
            field=models.SlugField(),
        ),
    ]
