# Generated by Django 2.1.1 on 2018-09-19 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sticker_collection_app', '0005_auto_20180701_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nationalteam',
            old_name='team_year',
            new_name='album',
        ),
    ]
